spring:
  datasource:
    url: jdbc:postgresql://acela.proxy.rlwy.net:44751/railway
    username: postgres
    password: eKMTpmkVzwKsNMPxAaqsdExCFwpekbNQ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update